name: Build LaTeX documents
on:
  push:
    tags-ignore:
      - '**'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build LaTeX documents
    # A Git ref in the repository istqb_product_base, which should be used for the CI definition
    uses: istqborg/istqb_product_base/.github/workflows/compile.yml@main
    with:
      skip-prerelease: true
      # A Git ref in the repository istqb_product_base, which should be used for the LaTeX+Markdown template
      base-version: main
