name: Build LaTeX documents
on:
  - push
permissions:
  contents: write
jobs:
  build:
    name: Build LaTeX documents
    # A git ref in the repository istqb_product_base, which should be used for the CI definition
    uses: istqborg/istqb_product_base/.github/workflows/compile.yml@fix/remove-submodule
    with:
      # A Git ref in the repository istqb_product_base, which should be used for the LaTeX+Markdown template
      base-version: fix/remove-submodule
